print("helloworld")
print('a','b','c')
print("add git")
print("where git in vscode shit")
print("a shit")
print("내 컴에서 git 개같이 부활")
print('숫자 두개 입력받기:')
a,b=input('숫자 두개입력 가능함?:').split()
#print(a)
#print(b)
sum4=int(a)+int(b)
print(sum4)
sum=int(a)-int(b)
print(sum)
sum2=int(a)*int(b)
print(sum2)
sum3=int(a)/int(b)
print(sum3)
sum5=int(a)%int(b)
print(sum5)
print('여기까지 문제없이 사칙연산이 잘되나 확인')
juna=input('문자입력')
june=('joonas')
#index1 = mstring.find('joonas')
#final1= mtring[:index1]+'??!'
#if(juna==june) :
#    print(final1)
#백준 ??!까지 풀다가 말았음

